# GoReleaser configuration for decider
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: decider
    main: ./cmd/decider
    binary: decider
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: sventorben
    name: decider
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## What's Changed

    See [CHANGELOG.md](CHANGELOG.md) for details.
  footer: |
    ---

    **Full Changelog**: https://github.com/sventorben/decider/compare/{{ .PreviousTag }}...{{ .Tag }}
