package cli

import (
	"fmt"
	"os"
	"path/filepath"
)

// InitConfig holds configuration for the init command.
type InitConfig struct {
	Dir    string
	Output *Output
}

// RunInit bootstraps the ADR directory structure.
func RunInit(cfg *InitConfig) error {
	adrDir := cfg.Dir
	templatesDir := filepath.Join(adrDir, "templates")

	// Create directories
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		return fmt.Errorf("creating directories: %w", err)
	}
	cfg.Output.Println("Created %s", adrDir)

	// Create template if it doesn't exist
	templatePath := filepath.Join(templatesDir, "adr.md")
	if _, err := os.Stat(templatePath); os.IsNotExist(err) {
		if err := os.WriteFile(templatePath, []byte(defaultTemplate), 0644); err != nil {
			return fmt.Errorf("creating template: %w", err)
		}
		cfg.Output.Println("Created %s", templatePath)
	} else {
		cfg.Output.Println("Template already exists: %s", templatePath)
	}

	// Create empty index.yaml if it doesn't exist
	indexPath := filepath.Join(adrDir, "index.yaml")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		emptyIndex := `# AUTO-GENERATED by decider index - DO NOT EDIT
generated_at: ""
adr_count: 0
adrs: []
`
		if err := os.WriteFile(indexPath, []byte(emptyIndex), 0644); err != nil {
			return fmt.Errorf("creating index: %w", err)
		}
		cfg.Output.Println("Created %s", indexPath)
	} else {
		cfg.Output.Println("Index already exists: %s", indexPath)
	}

	cfg.Output.Success("DECIDER initialized in %s", adrDir)
	return nil
}

const defaultTemplate = `---
adr_id: ADR-NNNN
title: "Your Decision Title Here"
status: proposed
date: YYYY-MM-DD
scope:
  paths:
    - "path/to/affected/**"
tags:
  - tag1
  - tag2
constraints:
  - "First constraint that MUST be followed"
  - "Second constraint"
invariants:
  - "Property that must always hold true"
supersedes: []
superseded_by: []
related_adrs: []
---

# ADR-NNNN: Your Decision Title Here

## Context

Describe the context and background that led to this decision. What problem are we solving? What forces are at play?

## Decision

State the decision clearly and concisely. Explain the reasoning behind the choice.

## Alternatives Considered

| Alternative | Pros | Cons |
|-------------|------|------|
| **Option A** | Benefits | Drawbacks |
| **Option B** | Benefits | Drawbacks |

## Consequences

**Positive:**
- First positive consequence
- Second positive consequence

**Negative:**
- First negative consequence (and mitigation if any)

## Agent Guidance

_Optional section. Include specific instructions for AI agents working in the affected scope._

When working in this area:
- Specific guidance point 1
- Specific guidance point 2
`
